### ISSUE TITLE
vnstudio 2.8下飞马柜台只能查到资金，界面中没有持仓，也看不到委托

### ISSUE THREAD

**Issue by cawind2** [vnpy/vnpy_femas#4]
vnstudio 2.8下飞马柜台只能查到资金，界面中没有持仓，也看不到委托

**Comment by vnpy** [comment]
请在cmd中用python -m vnstation启动程序，登录后截图下CMD里是否有什么报错？

**Comment by cawind2** [comment]
是insertDate, 估计是格式错误了
持仓数据可以查到了

**Comment by cawind2** [comment]
成交回报，委托回报的 insertDate，数据格式问题

**Comment by cawind2** [comment]
成交回报，委托回报的 insertDate，数据格式问题

**Comment by vnpy** [comment]
请使用最新的3.3.0版本VeighNa Studio测试下看看是否还会有问题
