### ISSUE TITLE
遇到一个femas很奇怪的问题

### ISSUE THREAD

**Issue by cawind2** [vnpy/vnpy_femas#5]
使用no_ui，algo_trading脚本，如果连接ctp柜台，取持仓没问题，但连接femas柜台，取持仓就是空值，如果用pycharm在debug下，能取到持仓，在运行模式下取不到。使用sleep(20)，也不行。

1。test1.py
.......
def run_child():
    """
    Running in the child process.
    """
    SETTINGS["log.file"] = True

    event_engine = EventEngine()
    main_engine = MainEngine(event_engine)
    # main_engine.add_gateway(CtpGateway)
    main_engine.add_gateway(FemasGateway)
    algo_engine = main_engine.add_app(AlgoTradingApp)
    main_engine.write_log("主引擎创建成功")

    log_engine = main_engine.get_engine("log")
    event_engine.register(EVENT_ALGO_LOG, log_engine.process_log_event)
    main_engine.write_log("注册日志事件监听")

    # main_engine.connect(setting, "CTP")
    main_engine.connect(setting, "FEMAS")
    # main_engine.write_log("连接CTP接口")
    main_engine.write_log("连接FEMAS接口")
    main_engine.write_log(f"用户名: {setting['用户名']}")

    sleep(10)

    algo_engine.init_engine()
    main_engine.write_log("引擎初始化完成")

    #algo_engine.init_all_strategies()
    #algo_engine.load_algo_template()
   
    # my algo trading
    algo_engine.add_algo_template(CalLostAlgo)
    sleep(5)   # Leave enough time to complete strategy initialization
    main_engine.write_log("引擎加载成功")

    #algo_engine.start_all_strategies()
    algo_engine.start_algo(algo_setting)
   
    while True:
        sleep(1)
        #main_engine.write_log("    子进程")

def run_parent():
    """
    Running in the parent process.
    """
    print("启动网络算法守护父进程")

    if trading and child_process is None:
            print("启动子进程")
            child_process = multiprocessing.Process(target=run_child)
            child_process.start()
            print("子进程启动成功")

2.test2.py  ----- my algo trading
  
 def on_start(self):
        print("开始")
        # 从柜台ctp读取仓位
        positions = self.algo_engine.main_engine.get_all_positions()
        print("wait 2.......")
        sleep(20)
        
        if positions is not None:
            print("get")
            print(positions)
        else:
            print("empty")

**Comment by vnpy** [comment]
请使用最新的3.3.0版本VeighNa Studio测试下看看是否还会有问题
