### ISSUE TITLE
vnpy2.8 飞马柜台下，订阅合约成功，但还是无法收到行情，行情服务器登录成功

### ISSUE THREAD

**Issue by cawind2** [vnpy/vnpy_femas#6]
使用ctp订阅合约没有问题，但使用飞马就不成功，代码中虽然可以查询到contract，subscribe也没报错，图中可以看到ctp柜台返回正确tick, 但femas就没有tick返回

[error.docx](https://github.com/vnpy/vnpy_femas/files/7852477/error.docx)

**Comment by vnpy** [comment]
请使用最新的3.3.0版本VeighNa Studio测试下看看是否还会有问题
